---

name: tests
on:
  pull_request:
    branch:
    - main
    types:
    - opened
    - reopened
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
    - run: go get -v -t -d ./...
    - run: go test -v ./...
