---

name: Lint & Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          cache: false

      - name: Set up Go environment
        run: go env -w CGO_ENABLED=0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          cache: false

      - name: Set up Go environment
        run: go env -w CGO_ENABLED=0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test ./...
